import '../styles/app.scss'

export const metadata = {
  title: 'React Lenis',
  description: 'Generated by create next app',
}
import SmoothScrolling from "../components/smooth-scrolling";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}